//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLOR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLOR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ds {
            get {
                object obj = ResourceManager.GetObject("ds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIICCgKCAgEA3imw+dcaIdfTrskA4+GD5SPD0buqJAIfb1Uk7Fgx8tIjEEhjrEEDbFdMrL+v/9nqVYBdctYULhzi63N3od46u6ZVYDGk5OBddy5WafTttFIjC5Oa6x3qUvPGpwNlV/zIowkX9kpTNLJqcSGIoiUd2lKJG+VqZI4HLZSeBzvhB0/4PKQsf6UVmwCFDwXuJrvE6FTT6ygr/orBSqlrK5FFQeMqKhxwqNQt1KGUMbrod7JLiyOz8b7GYMbJcztGPIuzj2IprlXpANsPXJniyupDrf72LsI0WC2VfJHs8y9I0vtYQCnu65DoEyxmQiU/k7lpjuyCJU3ve8yMD/ay7Skm+0jDUSgwRA8K2wfwM8i8zGYlsEcpUr0+vs3M5SMXkAgQPDE+lMRa5mo7J4haPfbNxMNZsDFd5RVxXSZ8OT28jNXUksfHFavAZ2IMxId3jo0lFCVhqBxILWYGFV3VuTA/nJtgPFjM0lJhNu6M83r4REcjFyBXf0ER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string publicK {
            get {
                return ResourceManager.GetString("publicK", resourceCulture);
            }
        }
    }
}
